<?php

namespace App\Http\Controllers\MiniApp;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Services\Telegram\TelegramInitDataValidator;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\Rule;
use Illuminate\Validation\UnauthorizedException;
use Illuminate\View\View;

class SessionController extends Controller
{
    public function __construct(
        private readonly TelegramInitDataValidator $validator,
    ) {
    }

    /**
     * Entry point for the Mini App.
     *
     * Behaviour:
     *   1. If the user is already authenticated, redirect straight to /app/home.
     *   2. In local demo mode, transparently auto-login the demo user.
     *   3. Otherwise, render the entry view which boots the Telegram SDK and
     *      immediately authenticates via JS.
     */
    public function entry(): View|RedirectResponse
    {
        if (auth('web')->check()) {
            return redirect()->route('app.home');
        }

        $acceptLang = (string) request()->header('Accept-Language', '');
        app()->setLocale(str_starts_with(strtolower($acceptLang), 'fa') ? 'fa' : 'en');

        if (app()->isLocal() && config('ads-platform.demo_mode')) {
            $user = User::firstOrCreate(
                ['telegram_user_id' => config('ads-platform.demo_telegram_user_id')],
                [
                    'display_name' => 'کاربر نمایشی',
                    'first_name' => 'کاربر',
                    'last_name' => 'نمایشی',
                    'telegram_username' => 'demo_user',
                    'locale' => 'fa',
                ],
            );
            Auth::guard('web')->login($user, true);

            return redirect()->route('app.home');
        }

        return view('app.entry');
    }

    /**
     * Authenticate the Mini App through trusted signals only.
     *
     * Accepted methods, in order:
     *   1. init_data: Telegram-signed Mini App initData.
     *   2. token: the high-entropy per-user magic token generated by the bot.
     *
     * IMPORTANT:
     * Telegram's initDataUnsafe is deliberately NOT accepted here. The object
     * exposed as initDataUnsafe is client-controlled and has no signature that
     * this server can verify. Trusting its `user.id` would allow an attacker to
     * submit another Telegram user id and impersonate that account.
     */
    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'init_data' => ['nullable', 'string', 'max:16384'],
            'token' => ['nullable', 'string', 'max:128'],
        ]);

        $telegramUser = null;
        $authMethod = 'none';

        // Layer 1: cryptographically signed Telegram initData.
        if (! empty($validated['init_data'])) {
            try {
                $data = $this->validator->validate($validated['init_data']);
                $telegramUser = $data['user'] ?? null;
                if (is_array($telegramUser) && isset($telegramUser['id'])) {
                    $authMethod = 'init_data';
                }
            } catch (UnauthorizedException) {
                // A valid magic token may still be present, so fall through.
            } catch (\Throwable $e) {
                Log::warning('SessionController: signed initData validation failed unexpectedly', [
                    'exception' => $e->getMessage(),
                ]);
            }
        }

        // Layer 2: the user's high-entropy magic token from the bot URL.
        if ($telegramUser === null && ! empty($validated['token'])) {
            try {
                $userByToken = User::where('magic_token', $validated['token'])->first();
            } catch (\Throwable $e) {
                Log::error('SessionController: magic_token lookup failed', [
                    'exception' => $e->getMessage(),
                ]);
                $userByToken = null;
            }

            if ($userByToken) {
                try {
                    $userByToken->forceFill(['last_seen_at' => now()])->saveQuietly();
                    Auth::guard('web')->login($userByToken);
                    $this->regenerateSessionSafely($request);

                    return response()->json([
                        'redirect' => route('app.home'),
                        'auth_method' => 'token',
                    ]);
                } catch (\Throwable $e) {
                    Log::error('SessionController: token-login failure', [
                        'exception' => $e->getMessage(),
                    ]);

                    return $this->fatalAuthError('token_login_failed');
                }
            }
        }

        if (! is_array($telegramUser) || ! isset($telegramUser['id'])) {
            return response()->json([
                'error' => 'telegram_user_missing',
                'message' => 'We could not securely identify your Telegram account. Please reopen the Mini App from the bot and try again.',
            ], 401);
        }

        $telegramUserId = filter_var($telegramUser['id'], FILTER_VALIDATE_INT);
        if (! $telegramUserId || $telegramUserId <= 0) {
            return response()->json([
                'error' => 'telegram_user_invalid',
                'message' => 'Telegram user data is invalid. Please reopen the Mini App from the bot and try again.',
            ], 401);
        }

        $locale = str_starts_with((string) ($telegramUser['language_code'] ?? ''), 'fa') ? 'fa' : 'en';
        $displayName = trim(($telegramUser['first_name'] ?? '').' '.($telegramUser['last_name'] ?? ''));

        try {
            $user = User::firstOrNew(['telegram_user_id' => (int) $telegramUserId]);
            $user->fill([
                'telegram_username' => $telegramUser['username'] ?? null,
                'first_name' => $telegramUser['first_name'] ?? null,
                'last_name' => $telegramUser['last_name'] ?? null,
                'display_name' => $displayName !== '' ? $displayName : 'Telegram user',
                'last_seen_at' => now(),
            ]);

            if (! $user->exists || ! in_array($user->locale, ['fa', 'en'], true)) {
                $user->locale = $locale;
            }

            $user->save();
        } catch (\Throwable $e) {
            Log::error('SessionController: user save failed', [
                'telegram_user_id' => $telegramUserId,
                'exception' => $e->getMessage(),
            ]);

            return $this->fatalAuthError('user_save_failed');
        }

        try {
            Auth::guard('web')->login($user);
            $this->regenerateSessionSafely($request);
        } catch (\Throwable $e) {
            Log::error('SessionController: session/login failure', [
                'exception' => $e->getMessage(),
            ]);

            return $this->fatalAuthError('session_failed');
        }

        // Avatar bytes are now served through our authenticated local proxy.
        // Do not persist or expose Telegram file URLs because those URLs embed
        // the bot token in their path.
        return response()->json([
            'redirect' => route('app.home'),
            'auth_method' => $authMethod,
        ]);
    }

    public function language(Request $request): RedirectResponse
    {
        $validated = $request->validate(['locale' => ['required', Rule::in(['fa', 'en'])]]);
        $user = $request->user();
        $user->locale = $validated['locale'];
        $user->locale_set_at = now();
        $user->save();

        return back();
    }

    public function locale(Request $request, string $locale): RedirectResponse
    {
        abort_unless(in_array($locale, ['fa', 'en'], true), 404);
        $user = $request->user();
        $user->locale = $locale;
        $user->locale_set_at = now();
        $user->save();

        return back();
    }

    public function destroy(Request $request): RedirectResponse
    {
        Auth::guard('web')->logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('app.entry');
    }

    private function regenerateSessionSafely(Request $request): void
    {
        try {
            $request->session()->regenerate();
        } catch (\Throwable $e) {
            Log::warning('SessionController: session regenerate failed, continuing', [
                'exception' => $e->getMessage(),
            ]);
        }
    }

    private function fatalAuthError(string $reason): JsonResponse
    {
        return response()->json([
            'error' => $reason,
            'message' => 'Temporary server issue. Please try again in a few seconds.',
            'retry_after_seconds' => 5,
        ], 500);
    }
}
