@extends('layouts.app')

@section('title', (app()->isLocale('fa') ? 'راهنما و قوانین' : 'Help and policies') . ' — ' . __('ui.brand'))

@section('content')
@php($isFa = app()->isLocale('fa'))
<header class="page-header"><div><div class="eyebrow">{{ $isFa ? 'پاسخ‌های روشن' : 'Clear answers' }}</div><h1 class="page-title">{{ $isFa ? 'راهنما و قوانین' : 'Help and policies' }}</h1><p class="page-lead">{{ $isFa ? 'قبل از ساخت کمپین، فرایند، محدودیت‌ها و قوانین محتوایی را مرور کنید.' : 'Review the workflow, limitations, and content rules before creating a campaign.' }}</p></div></header>

<section class="card card-soft">
    <div class="card-head"><div><h2 class="card-title">{{ $isFa ? 'Ads Platform چیست؟' : 'What is Ads Platform?' }}</h2></div><x-icon name="send" class="text-primary" /></div>
    <p>{{ $isFa ? 'Telegram Ads امکان نمایش تبلیغ در جایگاه‌های واجد شرایط Telegram را فراهم می‌کند. Ads Platform فرایند ثبت سفارش، پرداخت، بررسی اولیه، پیگیری وضعیت و مشاهده گزارش را در یک محیط ساده مدیریت می‌کند.' : 'Telegram Ads can place ads in eligible Telegram placements. Ads Platform brings order creation, payment, initial review, status tracking, and reporting into one simple workspace.' }}</p>
    <p class="muted" style="margin-bottom:0">{{ $isFa ? 'تصمیم نهایی درباره تأیید محتوا و زمان نمایش با Telegram است.' : 'Telegram makes the final decision on content approval and delivery timing.' }}</p>
</section>

<section class="section">
    <details class="accordion" open><summary>{{ $isFa ? 'بعد از ثبت سفارش چه اتفاقی می‌افتد؟' : 'What happens after I submit an order?' }}</summary><div class="accordion-body"><p>{{ $isFa ? 'پشتیبانی متن، مقصد و کانال‌های هدف را بررسی می‌کند. اگر اصلاح لازم باشد سفارش برای ویرایش برمی‌گردد؛ در غیر این صورت اپراتور آن را در Telegram ثبت می‌کند و وضعیت در صفحه کمپین به‌روزرسانی می‌شود.' : 'Support reviews the copy, destination, and target channels. If changes are needed, the order returns to you; otherwise an operator submits it to Telegram and updates the campaign timeline.' }}</p></div></details>
    <details class="accordion"><summary>{{ $isFa ? 'عنوان تبلیغ چیست؟' : 'What is the internal title?' }}</summary><div class="accordion-body"><p>{{ $isFa ? 'عنوان فقط برای مدیریت کمپین در حساب شماست و مخاطبان آن را نمی‌بینند.' : 'The title helps you organize campaigns and is never shown to the audience.' }}</p></div></details>
    <details class="accordion"><summary>{{ $isFa ? 'متن تبلیغ چه محدودیت‌هایی دارد؟' : 'What are the ad copy limits?' }}</summary><div class="accordion-body"><p>{{ $isFa ? 'متن حداکثر 160 نویسه است. شکست خط، فهرست، چند لینک، لینک کوتاه‌شده، فحاشی، نماد و ایموجی افراطی یا نوشتار گمراه‌کننده مجاز نیست.' : 'Copy is limited to 160 characters. Line breaks, lists, multiple or shortened links, profanity, excessive symbols or emoji, and misleading language are not allowed.' }}</p></div></details>
    <details class="accordion"><summary>{{ $isFa ? 'کانال هدف باید چه شرایطی داشته باشد؟' : 'Which channels are eligible targets?' }}</summary><div class="accordion-body"><p>{{ $isFa ? 'کانال باید عمومی، فعال، دارای محتوای کامل و مطابق حداقل عضو فعلی Telegram باشد. زبان کانال، متن و مقصد نیز باید مرتبط باشند.' : 'A channel must be public, active, complete, and meet Telegram’s current member threshold. The channel, copy, and destination should also match in language and subject.' }}</p></div></details>
    <details class="accordion"><summary>{{ $isFa ? 'محدودیت نمایش برای هر نفر چیست؟' : 'What is the per-user frequency cap?' }}</summary><div class="accordion-body"><p>{{ $isFa ? 'این عدد مشخص می‌کند یک کاربر در طول روز چند بار تبلیغ را ببیند. هر نمایش هزینه دارد؛ برای فروش مستقیم معمولاً تکرار کمتر و برای آگاهی از برند تکرار بیشتر انتخاب می‌شود.' : 'It controls how many times a person may see the ad per day. Every impression has a cost; direct-response campaigns often use a lower cap than brand-awareness campaigns.' }}</p></div></details>
    <details class="accordion"><summary>{{ $isFa ? 'پلن رقابتی چه تفاوتی دارد؟' : 'How is the Competitive plan different?' }}</summary><div class="accordion-body"><p>{{ $isFa ? 'پلن رقابتی با CPM بالاتر، اولویت مزایده را بیشتر می‌کند؛ اما زمان شروع یا نتیجه را تضمین نمی‌کند.' : 'The Competitive plan uses a higher CPM for stronger auction priority, but it does not guarantee launch timing or results.' }}</p></div></details>
    <details class="accordion"><summary>{{ $isFa ? 'اگر Telegram تبلیغ را رد کند چه می‌شود؟' : 'What if Telegram rejects the ad?' }}</summary><div class="accordion-body"><p>{{ $isFa ? 'دلیل ثبت‌شده در صفحه کمپین نمایش داده می‌شود. بازپرداخت نقدی انجام نمی‌شود؛ پس از تطبیق مالی، فقط مبلغی که مصرف نشده و Telegram نیز قطعی کسر نکرده باشد به اعتبار تبلیغاتی داخلیِ غیرقابل‌برداشت تبدیل می‌شود.' : 'The recorded reason appears on the campaign page. No cash refund is issued; after reconciliation, only funds that were not spent and not finally deducted by Telegram become non-withdrawable internal ad credit.' }}</p></div></details>
</section>

<section class="section card">
    <div class="card-head"><div><h2 class="card-title">{{ $isFa ? 'چک‌لیست پیش از ارسال' : 'Pre-submission checklist' }}</h2><p class="card-subtitle">{{ $isFa ? 'این موارد احتمال برگشت برای اصلاح را کمتر می‌کند.' : 'These checks reduce avoidable revision requests.' }}</p></div></div>
    <div class="stack-sm">@foreach($isFa ? ['متن حداکثر 160 نویسه است.','متن و مقصد یک موضوع و زبان مشترک دارند.','مقصد فعال، کامل و قابل‌دسترسی است.','بیش از یک لینک یا لینک کوتاه‌شده وجود ندارد.','محتوا در گروه‌های ممنوع Telegram قرار نمی‌گیرد.'] : ['Copy is 160 characters or fewer.','The copy and destination match in subject and language.','The destination is active, complete, and accessible.','There is no extra or shortened link.','The content is not in a prohibited Telegram category.'] as $item)<div class="cluster"><span class="status-chip status-success"><x-icon name="check" size="sm" /></span><span>{{ $item }}</span></div>@endforeach</div>
</section>

<section class="section card card-warning"><div class="card-head"><div><h2 class="card-title">{{ $isFa ? 'محتوای ممنوع' : 'Prohibited content' }}</h2></div><x-icon name="warning" class="text-warning" /></div><p>{{ $isFa ? 'محتوای جنسی یا گرافیکی، نفرت و خشونت، نقض حقوق دیگران، فریب، تبلیغات سیاسی یا مذهبی، قمار، خدمات مالی مضر، درمان تأییدنشده، مواد و دخانیات، سلاح، بدافزار و محصولات غیرقانونی پذیرفته نمی‌شود. مثال‌ها جامع نیستند و متن کامل سیاست‌ها ملاک است.' : 'Sexual or graphic content, hate or violence, rights violations, deception, political or religious promotion, gambling, harmful financial products, unapproved medical claims, drugs and tobacco, weapons, malware, and illegal products are not accepted. Examples are not exhaustive; the full policy controls.' }}</p></section>
@endsection
