@extends('layouts.admin')

@section('title', __('ui.admin_nav.reports'))
@section('page-title', __('ui.admin_nav.reports'))

@section('content')
@php
    $isFa = app()->isLocale('fa');
    $safeRoute = static fn (string $name, array $parameters = []) => \Illuminate\Support\Facades\Route::has($name) ? route($name, $parameters) : '#';
    $data = $stats ?? [];
    $series = collect($revenueSeries ?? []);
    $statuses = collect($statusBreakdown ?? []);
    $payments = collect($paymentBreakdown ?? []);
    $categories = collect($topCategories ?? []);
    $maxSeries = max(1,(int)$series->max('gross_irr'));
    $maxStatus = max(1,(int)$statuses->max('count'));
    $maxCategory = max(1,(int)$categories->max('value'));
@endphp
<header class="page-header"><div><div class="eyebrow">{{ $isFa?'گزارش مالی و عملکرد':'Financial and performance reporting' }}</div><h1 class="page-title">{{ __('ui.admin_nav.reports') }}</h1><p class="page-lead">{{ $isFa?'تعهدهای سفارش‌های تأمین‌شده را جدا از مبالغ قطعی ثبت‌شده در دفتر کل ببینید.':'Review funded-order commitments separately from amounts finally posted to the ledger.' }}</p></div><div class="page-header-actions"><a class="btn btn-secondary" href="{{ $safeRoute('admin.reports.export',request()->query()) }}"><x-icon name="download" />CSV</a></div></header>
<form class="filters" method="get" action="{{ $safeRoute('admin.reports.index') }}"><div class="field"><label class="field-label" for="preset">{{ $isFa?'بازه':'Period' }}</label><select class="select" id="preset" name="preset"><option value="today" @selected(request('preset')==='today')>{{ __('ui.common.today') }}</option><option value="7d" @selected(request('preset')==='7d')>{{ __('ui.common.last_7_days') }}</option><option value="month" @selected(request('preset')==='month')>{{ $isFa?'ماه جاری شمسی':'Current Persian month' }}</option><option value="30d" @selected(request('preset','30d')==='30d')>{{ __('ui.common.last_30_days') }}</option><option value="custom" @selected(request('preset')==='custom')>{{ $isFa?'دلخواه':'Custom' }}</option></select></div><div class="field"><label class="field-label" for="date-from">{{ $isFa?'از':'From' }}</label><input class="input number" id="date-from" name="from" type="date" value="{{ request('from') }}"></div><div class="field"><label class="field-label" for="date-to">{{ $isFa?'تا':'To' }}</label><input class="input number" id="date-to" name="to" type="date" value="{{ request('to') }}"></div><button class="btn btn-secondary" type="submit"><x-icon name="filter" />{{ $isFa?'اعمال بازه':'Apply' }}</button></form>
<div class="metric-grid"><div class="metric"><div class="metric-label">{{ $isFa?'فروش تأمین‌شده':'Funded sales' }}</div><div class="metric-value number">{{ number_format(intdiv((int)data_get($data,'gross_sales_irr',0),10)) }}</div><div class="metric-delta">{{ $isFa?'ارزش سفارش‌های پرداخت‌شده، تومان':'Paid order value, Toman' }}</div></div><div class="metric"><div class="metric-label">{{ $isFa?'بودجه رسانه رزروشده':'Reserved media budget' }}</div><div class="metric-value number">{{ number_format(intdiv((int)data_get($data,'media_cost_irr',0),10)) }}</div><div class="metric-delta">{{ $isFa?'تعهد سفارش؛ نه هزینه قطعی':'Order commitment, not final spend' }}</div></div><div class="metric"><div class="metric-label">{{ $isFa?'کارمزد قراردادشده':'Committed service fee' }}</div><div class="metric-value number">{{ number_format(intdiv((int)data_get($data,'service_revenue_irr',0),10)) }}</div><div class="metric-delta">{{ $isFa?'تا پیش از تسویه، درآمد قطعی نیست':'Not realized until settlement' }}</div></div><div class="metric"><div class="metric-label">{{ $isFa?'حاشیه قراردادشده':'Committed margin' }}</div><div class="metric-value number">{{ number_format(intdiv((int)data_get($data,'net_profit_irr',0),10)) }}</div><div class="metric-delta">{{ $isFa?'پیش از هزینه عملیاتی و تعدیلات':'Before operating costs and adjustments' }}</div></div></div>

<div class="metric-grid section"><div class="metric"><div class="metric-label">{{ $isFa?'تسویه قطعی دفتر کل':'Final ledger settlement' }}</div><div class="metric-value number">{{ number_format(intdiv((int)data_get($data,'realized_settlement_irr',0),10)) }}</div><div class="metric-delta">{{ $isFa?'رسانه + خدمات + بازیافت کارمزد':'Media + service + fee recovery' }}</div></div><div class="metric"><div class="metric-label">{{ $isFa?'درآمد خدمات قطعی':'Realized service revenue' }}</div><div class="metric-value number">{{ number_format(intdiv((int)data_get($data,'realized_service_revenue_irr',0),10)) }}</div><div class="metric-delta">{{ $isFa?'فقط ثبت‌های نهایی دفتر کل':'Final ledger postings only' }}</div></div><div class="metric"><div class="metric-label">{{ $isFa?'نمایش تحویل‌شده در بازه':'Delivered impressions' }}</div><div class="metric-value number">{{ number_format((int)data_get($data,'delivered_impressions',0)) }}</div><div class="metric-delta">{{ $isFa?'اختلاف snapshotهای تجمعی':'Delta of cumulative snapshots' }}</div></div><div class="metric"><div class="metric-label">{{ $isFa?'سفارش پرداخت‌شده':'Paid orders' }}</div><div class="metric-value number">{{ number_format((int)data_get($data,'paid_orders',0)) }}</div><div class="metric-delta">{{ $isFa?'تأمین‌شده در این بازه':'Funded in this period' }}</div></div></div>

<div class="two-column section" style="align-items:start">
    <section class="card chart-card"><div class="card-head"><div><h2 class="card-title">{{ $isFa?'روند فروش تأمین‌شده':'Funded sales trend' }}</h2><p class="card-subtitle">{{ $isFa?'ارزش سفارش‌هایی که همان روز تأمین مالی شدند':'Value of orders funded each day' }}</p></div></div>@if($series->isEmpty())<x-empty-state icon="chart" :description="__('ui.empty.data')" style="min-height:220px" />@else<div class="bar-list">@foreach($series as $point)<div class="bar-row"><div class="bar-row-meta"><span class="number">{{ data_get($point,'label',data_get($point,'date','—')) }}</span><strong class="number">{{ number_format(intdiv((int)data_get($point,'gross_irr',0),10)) }}</strong></div><div class="bar-track"><span class="bar-fill" style="--bar:{{ min(100,((int)data_get($point,'gross_irr',0)/$maxSeries)*100) }}%"></span></div></div>@endforeach</div>@endif</section>
    <section class="card chart-card"><div class="card-head"><div><h2 class="card-title">{{ $isFa?'وضعیت سفارش‌ها':'Order status distribution' }}</h2><p class="card-subtitle">{{ $isFa?'تعداد سفارش در هر مرحله':'Orders in each lifecycle stage' }}</p></div></div>@if($statuses->isEmpty())<x-empty-state icon="campaign" :description="__('ui.empty.data')" style="min-height:220px" />@else<div class="bar-list">@foreach($statuses as $row)@php($value=data_get($row,'status',data_get($row,'label','unknown')))<div class="bar-row"><div class="bar-row-meta"><span>{{ \Illuminate\Support\Facades\Lang::has('ui.status.'.$value)?__('ui.status.'.$value):str($value)->replace('_',' ')->title() }}</span><strong class="number">{{ data_get($row,'count',0) }}</strong></div><div class="bar-track"><span class="bar-fill" style="--bar:{{ min(100,((int)data_get($row,'count',0)/$maxStatus)*100) }}%"></span></div></div>@endforeach</div>@endif</section>
</div>

<div class="two-column section" style="align-items:start">
    <section class="card"><div class="card-head"><div><h2 class="card-title">{{ $isFa?'روش‌های پرداخت':'Payment methods' }}</h2></div></div>@if($payments->isEmpty())<p class="muted">{{ __('ui.empty.data') }}</p>@else<div class="stack-sm">@foreach($payments as $row)<div class="cluster-between"><span class="cluster"><span class="quick-icon"><x-icon name="transaction" /></span><strong>{{ strtoupper((string)data_get($row,'provider','other')) }}</strong></span><span><strong class="number">{{ number_format((int)data_get($row,'count',0)) }}</strong><small class="muted number" style="display:block">{{ number_format(intdiv((int)data_get($row,'amount_irr',0),10)) }}</small></span></div>@endforeach</div>@endif</section>
    <section class="card"><div class="card-head"><div><h2 class="card-title">{{ $isFa?'دسته‌های برتر کانال':'Top channel categories' }}</h2></div></div>@if($categories->isEmpty())<p class="muted">{{ __('ui.empty.data') }}</p>@else<div class="bar-list">@foreach($categories as $row)<div class="bar-row"><div class="bar-row-meta"><span>{{ data_get($row,'label','—') }}</span><strong class="number">{{ number_format((int)data_get($row,'value',0)) }}</strong></div><div class="bar-track"><span class="bar-fill" style="--bar:{{ min(100,((int)data_get($row,'value',0)/$maxCategory)*100) }}%"></span></div></div>@endforeach</div>@endif</section>
</div>

<section class="section card card-soft"><div class="card-head"><div><h2 class="card-title">{{ $isFa?'تعریف شاخص‌ها':'Metric definitions' }}</h2></div><x-icon name="document" class="text-primary" /></div><dl class="definition-list"><div class="definition-row"><dt>{{ $isFa?'فروش تأمین‌شده':'Funded sales' }}</dt><dd>{{ $isFa?'ارزش سفارش‌هایی که در بازه از کیف پول یا درگاه تأمین مالی شده‌اند':'Order value funded by wallet or gateway during the period' }}</dd></div><div class="definition-row"><dt>{{ $isFa?'تسویه قطعی':'Final settlement' }}</dt><dd>{{ $isFa?'فقط مبالغی که پس از تطبیق اپراتور در حساب‌های درآمد/هزینه دفتر کل ثبت شده‌اند':'Only amounts posted to ledger revenue/cost accounts after operator reconciliation' }}</dd></div><div class="definition-row"><dt>{{ $isFa?'نمایش در بازه':'Period impressions' }}</dt><dd>{{ $isFa?'اختلاف آخرین snapshot تا پایان بازه با آخرین snapshot پیش از شروع بازه؛ snapshotها با هم جمع نمی‌شوند':'Latest cumulative snapshot by period end minus the latest baseline before the period; snapshots are never summed' }}</dd></div></dl></section>
@endsection
