@extends('layouts.admin')

@section('title', __('ui.admin_nav.kyc'))
@section('page-title', __('ui.admin_nav.kyc'))

@section('content')
@php
    $isFa = app()->isLocale('fa');
    $safeRoute = static fn (string $name, array $parameters = []) => \Illuminate\Support\Facades\Route::has($name) ? route($name, $parameters) : '#';
    $source = $applications ?? $kycApplications ?? collect();
    $source = is_array($source) ? collect($source) : $source;
    $items = collect(is_object($source) && method_exists($source, 'items') ? $source->items() : $source);
    $formatDate = static function ($value): string { if (!$value) return '—'; try { return \App\Support\PersianDate::format(\Illuminate\Support\Carbon::parse($value)); } catch (\Throwable) { return (string) $value; } };
@endphp
<header class="page-header"><div><div class="eyebrow">{{ $isFa ? 'بررسی دستی مدارک' : 'Manual document review' }}</div><h1 class="page-title">{{ __('ui.admin_nav.kyc') }}</h1><p class="page-lead">{{ $isFa ? 'مدارک حساس فقط در صفحه جزئیات و با ثبت مشاهده نمایش داده می‌شوند.' : 'Sensitive documents are revealed only on the detail page with audited access.' }}</p></div></header>
<form class="filters" method="get" action="{{ $safeRoute('admin.kyc.index') }}"><div class="field field-search"><label class="field-label" for="kyc-q">{{ __('ui.actions.search') }}</label><input class="input" id="kyc-q" name="q" value="{{ request('q') }}" placeholder="{{ $isFa ? 'نام، تلفن یا Telegram ID' : 'Name, phone, or Telegram ID' }}"></div><div class="field"><label class="field-label" for="kyc-status">{{ __('ui.common.status') }}</label><select class="select" id="kyc-status" name="status"><option value="">{{ __('ui.common.all') }}</option>@foreach(['submitted','under_review','changes_requested','approved','rejected_permanent'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ __('ui.status.'.($status==='rejected_permanent'?'rejected':$status)) }}</option>@endforeach</select></div><button class="btn btn-secondary" type="submit"><x-icon name="filter" />{{ __('ui.actions.filter') }}</button></form>
@if($items->isEmpty())<x-empty-state icon="identity" :description="__('ui.empty.data')" />@else<div class="table-wrap"><table class="data-table"><thead><tr><th>{{ __('ui.common.user') }}</th><th>{{ __('ui.common.status') }}</th><th>{{ $isFa ? 'ارسال‌شده' : 'Submitted' }}</th><th>{{ $isFa ? 'بررسی‌کننده' : 'Reviewer' }}</th><th>{{ __('ui.common.actions') }}</th></tr></thead><tbody>@foreach($items as $application)@php($user=data_get($application,'user'));@php($id=data_get($application,'id'))<tr><td data-label="{{ __('ui.common.user') }}"><div class="table-primary"><span class="avatar">@if(data_get($user,'id'))<img src="@avatarUrl($user)" alt="" decoding="async" loading="lazy" onerror="this.style.display='none'; this.parentElement.classList.add('avatar-fallback')"><span class="avatar-initial" aria-hidden="true" style="display:none">{{ mb_strtoupper(mb_substr((string)data_get($user,'display_name','U'),0,1)) }}</span>@else{{ mb_strtoupper(mb_substr((string)data_get($user,'display_name','U'),0,1)) }}@endif</span><span class="table-primary-copy"><strong>{{ data_get($user,'display_name','—') }}</strong><small class="ltr">{{ data_get($user,'telegram_username') ? '@'.ltrim(data_get($user,'telegram_username'),'@') : data_get($user,'phone','—') }}</small></span></div></td><td data-label="{{ __('ui.common.status') }}"><x-status-chip :value="data_get($application,'status','submitted')" /></td><td data-label="{{ $isFa?'ارسال‌شده':'Submitted' }}" class="number">{{ $formatDate(data_get($application,'submitted_at',data_get($application,'created_at'))) }}</td><td data-label="{{ $isFa?'بررسی‌کننده':'Reviewer' }}">{{ data_get($application,'reviewer.name',$isFa?'تخصیص‌نیافته':'Unassigned') }}</td><td data-label="{{ __('ui.common.actions') }}"><div class="table-actions"><a class="btn btn-sm btn-secondary" href="{{ $safeRoute('admin.kyc.show',['application'=>$id]) }}">{{ $isFa ? 'بررسی مدارک' : 'Review' }}</a></div></td></tr>@endforeach</tbody></table></div>@if(method_exists($source,'links'))<div class="pagination">{{ $source->links() }}</div>@endif @endif
@endsection
