@extends('layouts.admin')

@section('title', __('ui.admin_nav.users'))
@section('page-title', __('ui.admin_nav.users'))

@section('content')
@php
    $isFa = app()->isLocale('fa');
    $safeRoute = static fn (string $name, array $parameters = []) => \Illuminate\Support\Facades\Route::has($name) ? route($name, $parameters) : '#';
    $source = $users ?? collect();
    $source = is_array($source) ? collect($source) : $source;
    $items = collect(is_object($source) && method_exists($source,'items') ? $source->items() : $source);
    $formatDate = static function ($value): string { if (!$value) return '—'; try { return \App\Support\PersianDate::format(\Illuminate\Support\Carbon::parse($value)); } catch (\Throwable) { return (string)$value; } };
@endphp
<header class="page-header"><div><div class="eyebrow">{{ $isFa?'پرونده مشتریان':'Customer records' }}</div><h1 class="page-title">{{ __('ui.admin_nav.users') }}</h1><p class="page-lead">{{ $isFa?'اطلاعات حساب، KYC، موجودی، سفارش‌ها و ریسک را از یک پرونده بررسی کنید.':'Review account details, KYC, balances, orders, and risk from one record.' }}</p></div></header>
<form class="filters" method="get" action="{{ $safeRoute('admin.users.index') }}"><div class="field field-search"><label class="field-label" for="user-q">{{ __('ui.actions.search') }}</label><input class="input" id="user-q" name="q" value="{{ request('q') }}" placeholder="{{ $isFa?'نام، یوزرنیم، تلفن یا Telegram ID':'Name, username, phone, or Telegram ID' }}"></div><div class="field"><label class="field-label" for="kyc-level">KYC</label><select class="select" id="kyc-level" name="kyc_level"><option value="">{{ __('ui.common.all') }}</option><option value="base" @selected(request('kyc_level')==='base')>{{ __('ui.status.base') }}</option><option value="rial_verified" @selected(request('kyc_level')==='rial_verified')>{{ __('ui.status.rial_verified') }}</option><option value="restricted" @selected(request('kyc_level')==='restricted')>{{ $isFa?'محدود':'Restricted' }}</option></select></div><div class="field"><label class="field-label" for="account-status">{{ $isFa?'حساب':'Account' }}</label><select class="select" id="account-status" name="account_status"><option value="">{{ __('ui.common.all') }}</option><option value="active">{{ $isFa?'فعال':'Active' }}</option><option value="suspended">{{ $isFa?'تعلیق':'Suspended' }}</option></select></div><button class="btn btn-secondary" type="submit"><x-icon name="filter" />{{ __('ui.actions.filter') }}</button></form>
@if($items->isEmpty())<x-empty-state icon="users" :description="__('ui.empty.data')" />@else<div class="table-wrap"><table class="data-table"><thead><tr><th>{{ __('ui.common.user') }}</th><th>KYC</th><th>{{ $isFa?'موجودی':'Balance' }}</th><th>{{ $isFa?'سفارش‌ها':'Orders' }}</th><th>{{ $isFa?'آخرین فعالیت':'Last active' }}</th><th>{{ __('ui.common.status') }}</th><th>{{ __('ui.common.actions') }}</th></tr></thead><tbody>@foreach($items as $user)<tr><td data-label="{{ __('ui.common.user') }}"><div class="table-primary"><span class="avatar">@if(data_get($user,'id'))<img src="@avatarUrl($user)" alt="" decoding="async" loading="lazy" onerror="this.style.display='none'; this.parentElement.classList.add('avatar-fallback')"><span class="avatar-initial" aria-hidden="true" style="display:none">{{ mb_strtoupper(mb_substr((string)data_get($user,'display_name','U'),0,1)) }}</span>@else{{ mb_strtoupper(mb_substr((string)data_get($user,'display_name','U'),0,1)) }}@endif</span><span class="table-primary-copy"><strong>{{ data_get($user,'display_name','—') }}</strong><small class="ltr">{{ data_get($user,'telegram_username') ? '@'.ltrim(data_get($user,'telegram_username'),'@') : 'ID '.data_get($user,'telegram_user_id','—') }}</small></span></div></td><td data-label="KYC"><x-status-chip :value="data_get($user,'kyc_level','base')" /></td><td data-label="{{ $isFa?'موجودی':'Balance' }}" class="number">{{ number_format(intdiv((int)data_get($user,'wallet_balance_irr',data_get($user,'balance_irr',0)),10)) }}</td><td data-label="{{ $isFa?'سفارش‌ها':'Orders' }}" class="number">{{ number_format((int)data_get($user,'orders_count',0)) }}</td><td data-label="{{ $isFa?'آخرین فعالیت':'Last active' }}" class="number">{{ $formatDate(data_get($user,'last_seen_at')) }}</td><td data-label="{{ __('ui.common.status') }}"><x-status-chip :value="data_get($user,'account_status','active')" /></td><td data-label="{{ __('ui.common.actions') }}"><div class="table-actions"><a class="btn btn-sm btn-secondary" href="{{ $safeRoute('admin.users.show',['user'=>data_get($user,'id')]) }}">{{ $isFa?'بررسی کامل':'Inspect' }}</a></div></td></tr>@endforeach</tbody></table></div>@if(method_exists($source,'links'))<div class="pagination">{{ $source->links() }}</div>@endif @endif
@endsection
