@extends('layouts.admin')

@section('title', __('ui.admin_nav.orders'))
@section('page-title', __('ui.admin_nav.orders'))

@section('content')
@php
    $isFa = app()->isLocale('fa');
    $safeRoute = static fn (string $name, array $parameters = []) => \Illuminate\Support\Facades\Route::has($name) ? route($name, $parameters) : '#';
    $source = $orders ?? [];
    $items = collect(is_object($source) && method_exists($source, 'items') ? $source->items() : $source);
    $formatDate = static function ($value): string { if (!$value) return '—'; try { return \Illuminate\Support\Carbon::parse($value)->format('Y/m/d H:i'); } catch (\Throwable) { return (string) $value; } };
@endphp
<header class="page-header"><div><div class="eyebrow">{{ $isFa ? 'صف عملیاتی کمپین‌ها' : 'Campaign operations queue' }}</div><h1 class="page-title">{{ __('ui.admin_nav.orders') }}</h1><p class="page-lead">{{ $isFa ? 'سفارش‌ها را بر اساس مرحله، پرداخت، اپراتور یا تاریخ فیلتر کنید.' : 'Filter orders by lifecycle, payment, operator, or date.' }}</p></div></header>
<form class="filters" method="get" action="{{ $safeRoute('admin.orders.index') }}"><div class="field field-search"><label class="field-label" for="order-q">{{ __('ui.actions.search') }}</label><input class="input" id="order-q" name="q" value="{{ request('q') }}" placeholder="{{ $isFa ? 'شناسه، عنوان یا کاربر' : 'ID, title, or user' }}"></div><div class="field"><label class="field-label" for="order-status">{{ __('ui.common.status') }}</label><select class="select" id="order-status" name="status"><option value="">{{ __('ui.common.all') }}</option>@foreach(['support_review','changes_requested','queued_for_telegram','telegram_review','telegram_approved','scheduled','active','pause_requested','paused','telegram_rejected','completed','manual_attention'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ __('ui.status.'.$status) }}</option>@endforeach</select></div><div class="field"><label class="field-label" for="payment-status">{{ $isFa ? 'پرداخت' : 'Payment' }}</label><select class="select" id="payment-status" name="payment_status"><option value="">{{ __('ui.common.all') }}</option>@foreach(['unfunded','pending','paid','partially_refunded','refunded','chargeback'] as $paymentStatus)<option value="{{ $paymentStatus }}" @selected(request('payment_status')===$paymentStatus)>{{ \Illuminate\Support\Facades\Lang::has('ui.status.'.$paymentStatus)?__('ui.status.'.$paymentStatus):str($paymentStatus)->replace('_',' ')->headline() }}</option>@endforeach</select></div><button class="btn btn-secondary" type="submit"><x-icon name="filter" />{{ __('ui.actions.filter') }}</button></form>
@if($items->isEmpty())
    <x-empty-state icon="campaign" :description="__('ui.empty.data')" />
@else
    <div class="table-wrap"><table class="data-table"><thead><tr><th>{{ __('ui.common.order') }}</th><th>{{ __('ui.common.user') }}</th><th>{{ __('ui.common.amount') }}</th><th>{{ $isFa ? 'پرداخت' : 'Payment' }}</th><th>{{ __('ui.common.status') }}</th><th>{{ __('ui.common.date') }}</th><th>{{ __('ui.common.actions') }}</th></tr></thead><tbody>@foreach($items as $order)@php($id=data_get($order,'public_id',data_get($order,'id')))<tr><td data-label="{{ __('ui.common.order') }}"><div class="table-primary"><span class="quick-icon"><x-icon name="campaign" /></span><span class="table-primary-copy"><strong>{{ data_get($order,'currentRevision.internal_title',data_get($order,'current_revision.internal_title',$isFa?'کمپین بدون عنوان':'Untitled campaign')) }}</strong><small class="number">#{{ $id }}</small></span></div></td><td data-label="{{ __('ui.common.user') }}"><div class="table-primary"><span class="avatar">{{ mb_strtoupper(mb_substr((string)data_get($order,'user.display_name','U'),0,1)) }}</span><span class="table-primary-copy"><strong>{{ data_get($order,'user.display_name','—') }}</strong><small class="ltr">{{ data_get($order,'user.telegram_username') ? '@'.ltrim(data_get($order,'user.telegram_username'),'@') : data_get($order,'user.telegram_user_id','—') }}</small></span></div></td><td data-label="{{ __('ui.common.amount') }}" class="number">{{ number_format(intdiv((int)data_get($order,'total_irr',0),10)) }} {{ $isFa?'تومان':'Toman' }}</td><td data-label="{{ $isFa?'پرداخت':'Payment' }}"><x-status-chip :value="data_get($order,'payment_status','unfunded')" /></td><td data-label="{{ __('ui.common.status') }}"><x-status-chip :value="data_get($order,'status','draft')" /></td><td data-label="{{ __('ui.common.date') }}" class="number">{{ $formatDate(data_get($order,'created_at')) }}</td><td data-label="{{ __('ui.common.actions') }}"><div class="table-actions"><a class="btn btn-sm btn-secondary" href="{{ $safeRoute('admin.orders.show',['order'=>$id]) }}">{{ __('ui.actions.view') }}</a></div></td></tr>@endforeach</tbody></table></div>
    @if(is_object($source) && method_exists($source,'links'))<div class="pagination">{{ $source->links() }}</div>@endif
@endif
@endsection
