@extends('layouts.admin')

@section('title', __('ui.admin_nav.channels'))
@section('page-title', __('ui.admin_nav.channels'))

@section('content')
@php
    $isFa = app()->isLocale('fa');
    $safeRoute = static fn (string $name, array $parameters = []) => \Illuminate\Support\Facades\Route::has($name) ? route($name, $parameters) : '#';
    $categoryItems = collect($categories ?? []);
    $source = $channels ?? collect();
    $source = is_array($source) ? collect($source) : $source;
    $channelItems = collect(is_object($source) && method_exists($source,'items') ? $source->items() : $source);
    $selectedCategory = $selectedCategory ?? $categoryItems->firstWhere('slug',request('category')) ?? null;
    $formatDate = static function ($value): string { if (!$value) return '—'; try { return \Illuminate\Support\Carbon::parse($value)->format('Y/m/d'); } catch (\Throwable) { return (string)$value; } };
@endphp
<header class="page-header"><div><div class="eyebrow">{{ $isFa?'کاتالوگ پیشنهاد به مشتری':'Customer recommendation catalog' }}</div><h1 class="page-title">{{ __('ui.admin_nav.channels') }}</h1><p class="page-lead">{{ $isFa?'تعداد دسته‌ها نامحدود است؛ هر دسته حداکثر ۳۰ کانال فعال دارد.':'Categories are unlimited; each can contain up to 30 active channels.' }}</p></div></header>

<div class="two-column" style="align-items:start;grid-template-columns:minmax(250px,.65fr) minmax(0,1.35fr)">
    <aside class="stack">
        <section class="card"><div class="card-head"><div><h2 class="card-title">{{ $isFa?'دسته‌بندی‌ها':'Categories' }}</h2><p class="card-subtitle number">{{ $categoryItems->count() }}</p></div></div><div class="stack-sm">@forelse($categoryItems as $category)@php($count=(int)(data_get($category,'channels_count')??collect(data_get($category,'channels',[]))->count()))<a class="queue-item" href="{{ $safeRoute('admin.channels.index',['category'=>data_get($category,'slug')]) }}"><span class="queue-icon" style="background:var(--ap-primary-soft);color:var(--ap-primary)"><x-icon name="channel" /></span><span class="queue-copy"><strong>{{ $isFa?data_get($category,'title_fa',data_get($category,'title_en')):data_get($category,'title_en',data_get($category,'title_fa')) }}</strong><small>{{ data_get($category,'is_active',true)?($isFa?'فعال':'Active'):($isFa?'غیرفعال':'Inactive') }}</small></span><span class="status-chip {{ $count>=30?'status-warning':'status-neutral' }} number">{{ $count }}/30</span></a>@empty<p class="muted">{{ $isFa?'هنوز دسته‌ای ساخته نشده است.':'No categories yet.' }}</p>@endforelse</div></section>
        <section class="card"><div class="card-head"><div><h2 class="card-title">{{ $isFa?'دسته جدید':'New category' }}</h2></div></div><form class="form-grid" action="{{ $safeRoute('admin.channels.categories.store') }}" method="post" data-loading-form>@csrf<div class="field"><label class="field-label required" for="category-fa">عنوان فارسی</label><input class="input" id="category-fa" name="title_fa" required></div><div class="field"><label class="field-label required" for="category-en">English title</label><input class="input ltr" id="category-en" name="title_en" required></div><div class="field"><label class="field-label required" for="category-slug">Slug</label><input class="input ltr" id="category-slug" name="slug" pattern="[a-z0-9-]+" required></div><button class="btn btn-primary btn-block" type="submit"><x-icon name="plus" />{{ $isFa?'ساخت دسته':'Create category' }}</button></form></section>
    </aside>

    <div class="stack">
        <section class="card">
            <div class="card-head"><div><h2 class="card-title">{{ $isFa?'افزودن کانال':'Add channel' }}</h2><p class="card-subtitle">{{ $isFa?'کانال عمومی و آخرین اطلاعات بررسی‌شده':'Public channel with latest verified details' }}</p></div><x-icon name="channel" class="text-primary" /></div>
            <form class="form-grid" action="{{ $safeRoute('admin.channels.store') }}" method="post" data-loading-form>@csrf<div class="field-row"><div class="field"><label class="field-label required" for="channel-title">{{ $isFa?'عنوان کانال':'Channel title' }}</label><input class="input" id="channel-title" name="title" required></div><div class="field"><label class="field-label required" for="channel-username">Username</label><input class="input ltr" id="channel-username" name="username" required placeholder="channel_name"></div></div><div class="field-row"><div class="field"><label class="field-label required" for="channel-url">Public URL</label><input class="input ltr" id="channel-url" name="public_url" type="url" required placeholder="https://t.me/channel"></div><div class="field"><label class="field-label" for="members-count">{{ $isFa?'تعداد عضو':'Member count' }}</label><input class="input number" id="members-count" name="members_count" type="number" min="0" value="0"></div></div><div class="field-row"><div class="field"><label class="field-label" for="channel-language">{{ $isFa?'زبان':'Language' }}</label><select class="select" id="channel-language" name="language"><option value="fa">فارسی</option><option value="en">English</option></select></div><div class="field"><label class="field-label required" for="channel-category">{{ $isFa?'دسته‌بندی':'Category' }}</label><select class="select" id="channel-category" name="category_ids[]" multiple required style="min-height:96px">@foreach($categoryItems as $category)<option value="{{ data_get($category,'id') }}">{{ $isFa?data_get($category,'title_fa'):data_get($category,'title_en') }}</option>@endforeach</select></div></div><label class="checkbox"><input type="checkbox" name="is_featured" value="1"><span>{{ $isFa?'در فهرست ویژه نمایش داده شود':'Feature this channel' }}</span></label><button class="btn btn-primary" type="submit"><x-icon name="plus" />{{ $isFa?'افزودن کانال':'Add channel' }}</button></form>
        </section>

        <section class="card"><div class="card-head"><div><h2 class="card-title">{{ $isFa?'فهرست کانال‌ها':'Channel list' }}</h2><p class="card-subtitle">{{ $selectedCategory ? ($isFa?data_get($selectedCategory,'title_fa'):data_get($selectedCategory,'title_en')) : __('ui.common.all') }}</p></div></div><form class="filters" method="get" action="{{ $safeRoute('admin.channels.index') }}"><div class="field field-search"><label class="field-label" for="channel-q">{{ __('ui.actions.search') }}</label><input class="input" id="channel-q" name="q" value="{{ request('q') }}" placeholder="{{ $isFa?'عنوان یا یوزرنیم':'Title or username' }}"></div><button class="btn btn-secondary" type="submit"><x-icon name="search" />{{ __('ui.actions.search') }}</button></form>@if($channelItems->isEmpty())<x-empty-state icon="channel" :description="__('ui.empty.data')" style="min-height:200px" />@else<div class="table-wrap"><table class="data-table"><thead><tr><th>{{ $isFa?'کانال':'Channel' }}</th><th>{{ $isFa?'عضو':'Members' }}</th><th>{{ $isFa?'واجد شرایط':'Eligibility' }}</th><th>{{ $isFa?'آخرین بررسی':'Last checked' }}</th><th>{{ __('ui.common.status') }}</th><th>{{ __('ui.common.actions') }}</th></tr></thead><tbody>@foreach($channelItems as $channel)<tr><td data-label="{{ $isFa?'کانال':'Channel' }}"><div class="table-primary"><span class="avatar">@if(data_get($channel,'avatar_url'))<img src="{{ data_get($channel,'avatar_url') }}" alt="">@else{{ mb_strtoupper(mb_substr((string)data_get($channel,'title','C'),0,1)) }}@endif</span><span class="table-primary-copy"><strong>{{ data_get($channel,'title','—') }}</strong><small class="ltr">{{ '@'.ltrim((string)data_get($channel,'username',''),'@') }}</small></span></div></td><td data-label="{{ $isFa?'عضو':'Members' }}" class="number">{{ number_format((int)data_get($channel,'members_count',0)) }}</td><td data-label="{{ $isFa?'واجد شرایط':'Eligibility' }}"><x-status-chip :value="data_get($channel,'eligibility_status','unverified')" /></td><td data-label="{{ $isFa?'آخرین بررسی':'Last checked' }}" class="number">{{ $formatDate(data_get($channel,'last_verified_at')) }}</td><td data-label="{{ __('ui.common.status') }}"><x-status-chip :value="data_get($channel,'is_active',true)?'active':'paused'" :label="data_get($channel,'is_active',true)?($isFa?'فعال':'Active'):($isFa?'غیرفعال':'Inactive')" /></td><td data-label="{{ __('ui.common.actions') }}"><div class="table-actions"><a class="btn btn-sm btn-secondary" href="{{ $safeRoute('admin.channels.edit',['channel'=>data_get($channel,'id')]) }}">{{ __('ui.actions.edit') }}</a></div></td></tr>@endforeach</tbody></table></div>@if(method_exists($source,'links'))<div class="pagination">{{ $source->links() }}</div>@endif @endif</section>
    </div>
</div>
@endsection
